---

- hosts: all

  tasks:
    - name: Change the hostname to our standard
      hostname:
        name="{{ inventory_hostname }}"
      when:
        ansible_fqdn != ansible_ssh_host

    - name: restart machine
      reboot:
      async: 0
      poll: 0
      ignore_errors: True
      when:
        reboot is defined

    - name: Fix /etc/hosts removing the old hostname
      tags:
        - hosts
      lineinfile:
        state=present
        dest=/etc/hosts
        line="{{ ansible_default_ipv4.address }}   {{ inventory_hostname }}"
        regexp="^{{ ansible_default_ipv4.address }}"
      when:
        ansible_fqdn != inventory_hostname

    - name: Validate ansible_fqdn == inventory_hostname
      tags:
        - validate
      assert:
        that:
          ansible_fqdn == inventory_hostname